### ISSUE TITLE
Updates not incrementing DNS Serial

### ISSUE THREAD

**Issue by pdisbrey** [m42e/certbot-dns-ispconfig#4]
When the plugin creates or deletes the dns TXT record, the serial number of the SOA is not incremented, therefore the slave dns servers are not updated.
ISPConfig version 3.1.15

**Comment by maximusVII** [comment]
How can update the script with pip to get this patch applied? 

I manually edited the file /usr/local/lib/python3.7/dist-packages/certbot_dns_ispconfig/dns_ispconfig.py and changed the following line `"update_serial": False,` to `"update_serial": True,` but the serial does still not get updated.

Any hints?

Thanks a lot
